<?php

namespace Database\Factories;

use App\Models\Post;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Post>
 */
class PostFactory extends Factory
{
    protected $model = Post::class;

    public function definition(): array
    {
        return [
            'title'     => fake()->sentence(5),
            'slug'      => '', // auto-generated by Post::booted() creating hook
            'body'      => fake()->paragraphs(3, true),
            'excerpt'   => fake()->sentence(15),
            'status'    => 'draft',
            'author'    => 'Pierre ADAM',
            'date'      => fake()->dateTimeBetween('-1 year', 'now'),
            'show_date' => true,
        ];
    }

    public function published(): static
    {
        return $this->state(['status' => 'published']);
    }

    public function draft(): static
    {
        return $this->state(['status' => 'draft']);
    }
}
